import {ESPLoader,Transport} from 'esptool-js';
import SparkMD5 from 'spark-md5';
const $=id=>document.getElementById(id);let port,reader,readTask,busy=false,sequence=0,lastState=null;const waiting=new Map();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function status(message){$('status').textContent=message;}
function lock(value){busy=value;for(const id of ['ssid','password','networks','model'])$(id).disabled=value;for(const id of ['install','existing','scan','connect','skip','disconnect'])$(id).disabled=value;$('existing').disabled=value||!navigator.serial;$('install').disabled=value||!$('model').checked||!navigator.serial;}
async function closeSerial(){if(reader)await reader.cancel().catch(()=>{});if(readTask)await readTask.catch(()=>{});reader=null;readTask=null;if(port?.readable)await port.close().catch(()=>{});for(const p of waiting.values()){clearTimeout(p.timer);p.reject(new Error('裝置已斷開'));}waiting.clear();}
async function startSerial(selected){port=selected;await port.open({baudRate:115200});await port.setSignals({dataTerminalReady:false,requestToSend:false});reader=port.readable.getReader();lastState=null;readTask=(async()=>{let text='';const decoder=new TextDecoder();try{while(true){const {value,done}=await reader.read();if(done)break;text+=decoder.decode(value,{stream:true});let n;while((n=text.indexOf('\n'))>=0){const line=text.slice(0,n);text=text.slice(n+1);let reply;try{reply=JSON.parse(line);}catch{continue;}if(!reply||typeof reply!=='object')continue;if(reply.event==='state')lastState=reply;if(reply.event==='wifi'&&waiting.has(reply.id)){const p=waiting.get(reply.id);clearTimeout(p.timer);waiting.delete(reply.id);p.resolve(reply);}}if(text.length>16384)text='';}}finally{reader?.releaseLock();}})();readTask.catch(()=>status('USB 已斷開，請重新接駁。'));}
async function send(payload){if(!port?.writable)throw new Error('請先連接裝置');const writer=port.writable.getWriter();try{await writer.write(new TextEncoder().encode('\n'+JSON.stringify(payload)+'\n'));}finally{writer.releaseLock();}}
async function rpc(action,extra={}){const id=String(++sequence);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{waiting.delete(id);reject(new Error('裝置未回應，請重試'));},15000);waiting.set(id,{resolve,reject,timer});send({cmd:'wifi',action,id,...extra}).catch(e=>{clearTimeout(timer);waiting.delete(id);reject(e);});});}
async function identify(){for(let i=0;i<20;i++){await send({cmd:'state'});await sleep(700);if(lastState?.app==='kmb-bus-clock'&&lastState.version)return;}throw new Error('請先安裝此頁提供的新版程式');}
async function scan(){const start=await rpc('scan');let r=start;for(let i=0;i<85&&r.stage!==0;i++){await sleep(700);r=await rpc('status');}if(r.stage!==0)throw new Error('搜尋較慢，可手動輸入網絡名稱');$('networks').replaceChildren(new Option('選網絡',''));for(const n of r.networks||[])$('networks').add(new Option(n.ssid,n.ssid));if(r.current){$('ssid').value=r.current;$('networks').value=r.current;}$('wifi-status').textContent=(r.networks?.length?'已找到網絡':r.message||'可手動輸入網絡名稱');}
async function afterConnection(){await identify();$('wifi-section').hidden=false;status('裝置已連接。下一步：Wi-Fi。');await scan().catch(e=>$('wifi-status').textContent=e.message);$('wifi-section').scrollIntoView({behavior:'smooth',block:'start'});}
$('model').addEventListener('change',()=>lock(busy));
$('install').addEventListener('click',async()=>{if(busy||!$('model').checked)return;let transport,loader;lock(true);try{if(port)await closeSerial();port=await navigator.serial.requestPort();const manifest=await fetch('manifest.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error('暫時未能讀取安裝包');return r.json();});const parts=[];for(const p of manifest.parts){const bytes=new Uint8Array(await fetch(p.path,{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error('下載失敗，請重試');return r.arrayBuffer();}));const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==p.sha256)throw new Error('安裝包校驗失敗，請重新載入網站');parts.push({data:bytes,address:p.offset});}
 status('連接裝置…');transport=new Transport(port,false);loader=new ESPLoader({transport,baudrate:115200,terminal:{clean(){},write(){},writeLine(){}},debugLogging:false});await loader.main();if(loader.chip.CHIP_NAME!=='ESP32')throw new Error('型號不支援；尚未寫入任何程式');const flashId=await loader.readFlashId();if(((flashId>>>16)&255)!==0x16)throw new Error('只支援 4MB 版本；尚未寫入任何程式');$('progress').hidden=false;const total=parts.reduce((n,p)=>n+p.data.length,0);const complete=parts.map(()=>0);await loader.writeFlash({fileArray:parts,flashMode:'keep',flashFreq:'keep',flashSize:'keep',eraseAll:false,compress:true,calculateMD5Hash:bytes=>SparkMD5.ArrayBuffer.hash(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)),reportProgress:(index,written,size)=>{complete[index]=Math.min(1,written/size)*parts[index].data.length;const value=Math.round(100*complete.reduce((a,b)=>a+b,0)/total);$('progress').value=value;status('安裝中 '+value+'% · 請勿拔線');}});await loader.after('hard_reset');await transport.disconnect();transport=null;$('progress').value=100;status('安裝完成，正在啟動…');await sleep(1200);await startSerial(port);await afterConnection();}
 catch(e){status(e.name==='NotFoundError'?'已取消選擇裝置':e.message||'安裝未完成，可重新按安裝');if(loader)await loader.after('hard_reset').catch(()=>{});if(transport)await transport.disconnect().catch(()=>{});}finally{lock(false);}});
$('existing').addEventListener('click',async()=>{lock(true);try{await closeSerial();const p=await navigator.serial.requestPort();await startSerial(p);await afterConnection();}catch(e){status(e.name==='NotFoundError'?'已取消':e.message);}finally{lock(false);}});
$('scan').addEventListener('click',async()=>{lock(true);try{await scan();}catch(e){$('wifi-status').textContent=e.message;}finally{lock(false);}});
$('networks').addEventListener('change',()=>{$('ssid').value=$('networks').value;});
$('connect').addEventListener('click',async()=>{const ssid=$('ssid').value,password=$('password').value;if(!ssid||new TextEncoder().encode(ssid).length>32){$('wifi-status').textContent='請選擇網絡';return;}const passBytes=new TextEncoder().encode(password).length;if(passBytes&&(passBytes<8||passBytes>63)){$('wifi-status').textContent='密碼需 8–63 個字元';return;}lock(true);$('cancel-network').hidden=false;try{let r=await rpc('connect',{ssid,password});$('password').value='';$('wifi-status').textContent='連接中…';for(let i=0;i<65&&r.stage!==0;i++){await sleep(700);r=await rpc('status');}if(r.stage!==0)throw new Error('連接較慢，請看裝置屏幕');if(!r.connected||r.current!==ssid||r.message!=='已連線')throw new Error(r.message||'未能連接，請檢查密碼');$('wifi-status').textContent='已連線';$('ready').hidden=false;$('ready').scrollIntoView({behavior:'smooth'});}catch(e){$('password').value='';$('wifi-status').textContent=e.message;}finally{$('cancel-network').hidden=true;lock(false);}});
$('cancel-network').addEventListener('click',async()=>{try{await rpc('cancel');$('wifi-status').textContent='已取消';}catch(e){$('wifi-status').textContent=e.message;}});
$('skip').addEventListener('click',()=>{$('ready').hidden=false;$('ready').scrollIntoView({behavior:'smooth'});});
$('disconnect').addEventListener('click',async()=>{await closeSerial();status('完成。可以直接使用屏幕。');});
if(!navigator.serial){status('首次安裝請用電腦 Chrome 或 Edge。');$('existing').disabled=true;}
fetch('manifest.json').then(r=>r.json()).then(m=>$('version').textContent='Beta '+m.version).catch(()=>{});
