[platformio]
core_dir = .platformio

[env:board]
platform = espressif32@7.1.2
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit ST7735 and ST7789 Library@1.11.0
  bblanchon/ArduinoJson@6.21.5
