#pragma once
#include <cmath>
#include <cstdint>
#include <algorithm>
struct GeoPoint{float lng,lat;};
struct MapPoint{int16_t x,y;};
constexpr int maxMapStops=64;
struct RoadData{bool valid=false;uint32_t gen=0;int count=0,approachCount=0;MapPoint points[256];float pointFractions[256]={};MapPoint stops[maxMapStops];uint32_t labels[maxMapStops];int stopSeq[maxMapStops]={};float stopFractions[maxMapStops]={};int leadSeq=0;float leadFraction=0;int stopCount=0;float meters=0,continuationMeters=0;};
struct RoadWindow{int first=0,last=0;GeoPoint start{};float meters=0;};
struct RoadContinuation{int last=0;GeoPoint finish{};float meters=0;};
struct WindowStop{GeoPoint point;uint32_t label;int seq;float fraction;WindowStop(GeoPoint p={},uint32_t l=0,int s=0,float f=0):point(p),label(l),seq(s),fraction(f){}};
inline float geoDistance2(GeoPoint a,GeoPoint b){float x=(a.lng-b.lng)*.925f,y=a.lat-b.lat;return x*x+y*y;}
inline float geoMeters(GeoPoint a,GeoPoint b){return std::sqrt(geoDistance2(a,b))*111320.0f;}
inline bool matchRoadEnd(const GeoPoint*p,int n,const GeoPoint*s,int ns,int&end){if(n<1||ns<1||ns>3)return false;float best[3]={1e9f,1e9f,1e9f};int chosen[3][3]={};for(int i=0;i<n;i++)for(int k=0;k<ns;k++){float v=geoDistance2(p[i],s[k])+(k?best[k-1]:0);if(v<best[k]){best[k]=v;if(k)for(int j=0;j<k;j++)chosen[k][j]=chosen[k-1][j];chosen[k][k]=i;}}for(int k=0;k<ns;k++)if(geoMeters(p[chosen[ns-1][k]],s[k])>150)return false;end=chosen[ns-1][ns-1];return true;}
inline RoadWindow upstreamWindow(const GeoPoint*p,int end,float budget=3000){RoadWindow w;w.first=w.last=end;w.start=p[end];float left=std::max(0.0f,budget);for(int i=end;i>0;i--){float d=geoMeters(p[i-1],p[i]);if(d>left&&d>0){float f=left/d;w.first=i;w.start={p[i].lng+(p[i-1].lng-p[i].lng)*f,p[i].lat+(p[i-1].lat-p[i].lat)*f};w.meters+=left;return w;}left-=d;w.meters+=d;w.first=i-1;w.start=p[i-1];}return w;}
inline float continuationBudget(float approachMeters){return approachMeters>0?std::max(150.0f,std::min(450.0f,approachMeters*.15f)):300.0f;}
inline RoadContinuation downstreamContinuation(const GeoPoint*p,int n,int start,float budget){RoadContinuation c;c.last=start;c.finish=p[start];float left=std::max(0.0f,budget);for(int i=start;i+1<n;i++){float d=geoMeters(p[i],p[i+1]);if(d>left&&d>0){float f=left/d;c.last=i;c.finish={p[i].lng+(p[i+1].lng-p[i].lng)*f,p[i].lat+(p[i+1].lat-p[i].lat)*f};c.meters+=left;return c;}left-=d;c.meters+=d;c.last=i+1;c.finish=p[i+1];}return c;}
inline float windowFraction(const GeoPoint*p,const RoadWindow&w,int index){if(w.meters<=0)return 0;float distance=geoMeters(w.start,p[w.first]);if(index<w.first){for(int i=index+1;i<=w.first;i++)distance-=geoMeters(p[i-1],p[i]);}else for(int i=w.first+1;i<=index;i++)distance+=geoMeters(p[i-1],p[i]);return distance/w.meters;}
inline bool projectWindow(const GeoPoint*p,const RoadWindow&w,const WindowStop*s,int ns,RoadData&out,const RoadContinuation*c=nullptr){if(ns<1||ns>maxMapStops)return false;bool hasContinuation=c&&c->meters>0;float minx=1e9,maxx=-1e9,miny=1e9,maxy=-1e9;auto bounds=[&](GeoPoint g){float x=g.lng*.925f,y=-g.lat;minx=std::min(minx,x);maxx=std::max(maxx,x);miny=std::min(miny,y);maxy=std::max(maxy,y);};bounds(w.start);for(int i=w.first;i<=w.last;i++)bounds(p[i]);if(hasContinuation){for(int i=w.last+1;i<=c->last;i++)bounds(p[i]);bounds(c->finish);}for(int i=0;i<ns;i++)bounds(s[i].point);float dx=std::max(maxx-minx,.00005f),dy=std::max(maxy-miny,.00005f),scale=std::min(104.f/dx,101.f/dy),ox=150+(104-dx*scale)/2,oy=49+(101-dy*scale)/2;auto project=[&](GeoPoint g){return MapPoint{(int16_t)std::lround(ox+(g.lng*.925f-minx)*scale),(int16_t)std::lround(oy+(-g.lat-miny)*scale)};};out.count=0;out.pointFractions[0]=0;out.points[out.count++]=project(w.start);int span=w.last-w.first,n=std::min(span+1,hasContinuation?253:255);for(int j=0;j<n;j++){int i=w.first+(n>1?(int)std::lround(j*span/float(n-1)):0);MapPoint m=project(p[i]);if(m.x==out.points[out.count-1].x&&m.y==out.points[out.count-1].y)continue;out.pointFractions[out.count]=windowFraction(p,w,i);out.points[out.count++]=m;}out.pointFractions[out.count-1]=1;out.approachCount=out.count;out.continuationMeters=hasContinuation?c->meters:0;if(hasContinuation){int available=256-out.count,downstreamSpan=std::max(0,c->last-w.last),samples=std::min(downstreamSpan,available-1);for(int j=1;j<=samples;j++){int i=w.last+(int)std::lround(j*downstreamSpan/float(samples));MapPoint m=project(p[i]);if(m.x==out.points[out.count-1].x&&m.y==out.points[out.count-1].y)continue;out.pointFractions[out.count]=1;out.points[out.count++]=m;}MapPoint finish=project(c->finish);if(out.count<256&&(finish.x!=out.points[out.count-1].x||finish.y!=out.points[out.count-1].y)){out.pointFractions[out.count]=1;out.points[out.count++]=finish;}}out.stopCount=ns;out.meters=w.meters;for(int i=0;i<ns;i++){out.stops[i]=project(s[i].point);out.labels[i]=s[i].label;out.stopSeq[i]=s[i].seq;out.stopFractions[i]=s[i].fraction;}out.valid=true;return true;}
